version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming the React app Dockerfile is in the root directory and named Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - express-backend
      - flask-backend

  express-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assuming the Express app Dockerfile is in the backend directory and named Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - flask-backend

  flask-backend:
    build:
      context: ./AppConsultas
      dockerfile: Dockerfile  # Assuming the Flask app Dockerfile is in the AppConsultas directory and named Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=agent-flask.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./AppConsultas:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
